---
# ✅ ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-app

---
# ✅ ConfigMap: vault-agent-config
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-config
data:
  config.hcl: |
    exit_after_auth = false
    pid_file = "/tmp/pidfile"

    vault {
      address = "http://192.168.137.57:8200"
    }

    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "vault-app"
        }
      }
    }

    cache {
      use_auto_auth_token = true
    }

    listener "tcp" {
      address = "127.0.0.1:8200"
      tls_disable = true
    }

---
# ✅ Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-compare-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-compare-ui
  template:
    metadata:
      labels:
        app: vault-compare-ui
    spec:
      serviceAccountName: vault-auth # <- Vault Role과 매핑된 SA
      containers:
        - name: web
          image: ghcr.io/sungeunsong/vault-compare-ui:latest
          ports:
            - containerPort: 3000
          env:
            - name: VAULT_ADDR
              value: "http://127.0.0.1:8200" # Vault Agent 프록시 주소
            - name: TRANSIT_KEY_TENANT_A
              value: "tenant-a-key"
            - name: TRANSIT_KEY_TENANT_B
              value: "tenant-b-key"

        - name: vault-agent
          image: docker.io/hashicorp/vault:1.15.0
          command: ["vault", "agent", "-config=/etc/vault/config.hcl"]
          volumeMounts:
            - name: vault-agent-config
              mountPath: /etc/vault

      volumes:
        - name: vault-agent-config
          configMap:
            name: vault-agent-config # Vault Agent 설정(ConfigMap)에서 불러옴

---
# ✅ Service
apiVersion: v1
kind: Service
metadata:
  name: vault-compare-ui
spec:
  type: LoadBalancer
  selector:
    app: vault-compare-ui
  ports:
    - port: 80
      targetPort: 3000

---

